/**
 * Generated from artifacts.yaml by scripts/gen_artifacts.py.
 *
 * Do NOT edit this file. Edit artifacts.yaml and run `just artifacts`.
 */

/**
 * The revisions of one contract an artifact implements.
 *
 * Two peers are compatible when their ranges overlap; they then
 * operate at the lower of the two `speaks`.
 */
export interface ContractRange {
  readonly speaks: number;
  readonly accepts: number;
}

/**
 * Where each artifact is. Says nothing about compatibility — that is
 * `CONTRACTS` below. The two must never be derived from one another.
 */
export const ARTIFACT_VERSIONS = {
  'switch-core': '0.21.1',
  'switch-console': '0.31.2',
  'agent-runtime': '0.3.3',
  sidecar: '1.9.5',
  gateway: '0.21.1',
  setup: '0.21.1',
  'helm-chart': '0.21.1',
  compose: '0.21.1',
  'switch-connector': '0.9.10',
  'switch-connector-codex': '0.3.11',
  'switch-connector-opencode': '0.1.6',
} as const satisfies Record<string, string>;

export type ArtifactName = keyof typeof ARTIFACT_VERSIONS;

/** The release version of an artifact. */
export function artifactVersion(artifact: ArtifactName): string {
  return ARTIFACT_VERSIONS[artifact];
}

export const CONTRACTS = {
  // The wire protocol between switch-core's agent bridge and an agent runtime: the event stream, its frame shapes, the resume cursor, and the tool-call channel.
  'agent-protocol': {
    'switch-core': { speaks: 1, accepts: 1 },
    'agent-runtime': { speaks: 1, accepts: 1 },
  },
  // The HTTP API switch-core serves to first-party UI clients. Excludes the authentication surface, which is deliberately frozen and unversioned so that a client can always authenticate far enough to be told what is wrong.
  'gateway-api': {
    'switch-core': { speaks: 1, accepts: 1 },
    'switch-console': { speaks: 1, accepts: 1 },
  },
  // The interface of the published standalone compose artifact — its service names, profiles, and environment variables — which Switch Console's local-server mode drives.
  'stack-compose': {
    'switch-console': { speaks: 1, accepts: 1 },
    compose: { speaks: 1, accepts: 1 },
  },
  // How Switch Console controls a deployed sidecar on a remote host: the ready file it reads, and the control channel it opens.
  'sidecar-control': {
    'switch-console': { speaks: 1, accepts: 1 },
    sidecar: { speaks: 1, accepts: 1 },
  },
  // The database schema switch-core expects. Internal to switch-core — this contract is never disclosed in an externally facing response.
  'db-schema': {
    'switch-core': { speaks: 1, accepts: 1 },
  },
} as const satisfies Record<string, Record<string, ContractRange>>;

export type ContractName = keyof typeof CONTRACTS;

/**
 * Return an artifact's declared range for a contract.
 *
 * Throws for a pair the registry does not know. An unregistered pair
 * is a bug in the caller, never a reason to assume a default — a wrong
 * default reads as compatible.
 */
export function contractRange(contract: string, artifact: string): ContractRange {
  const registry = CONTRACTS as Record<string, Record<string, ContractRange>>;
  const declared = registry[contract]?.[artifact];
  if (declared === undefined) {
    throw new Error(
      `artifacts.yaml declares no range for artifact '${artifact}' in contract '${contract}'`
    );
  }
  return declared;
}
