"""Who may run a session, and under which generation.

The stores refuse to decide this: `SessionLeaseStore.acquire` fails rather than
displacing anyone, and `take_over` only acts on a decision someone else made.
This is where the decision is made, once, for every door.

Three rules, and the whole slice is them:

- **The server mints the epoch.** The host does not choose its own generation,
  because the epoch is what the server fences stale events and commands with,
  and a value the sender picks fences nothing.
- **One holder.** A live holder is not displaced by accident. A host that means
  to take a running session from another asks for it, and a host whose lease has
  aged out is not holding anything to take.
- **A lease reaches no room.** Nothing here reads or writes a room association.
  Publication authority is a different fact with a different writer, and a host
  with a valid credential and a valid lease still cannot put itself in front of
  anyone.
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from switch_core.bridges.agent.sessions.errors import SessionApiError
from switch_core.bridges.agent.sessions.schemas import LeaseRequest, LeaseResponse
from switch_core.db.stores.session_lease_store import (
    LeaseHeld,
    LeaseMoved,
    SessionLeaseStore,
)
from switch_core.db.stores.session_store import SessionAlreadyRegistered, SessionStore

if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio import AsyncSession

    from switch_core.db.models import HostSession, SessionLease


def _mint_epoch() -> str:
    """A generation identifier, opaque and never parsed.

    Random rather than counted: a counter would have to be read from somewhere,
    and the one thing an epoch must never do is repeat after the state that knew
    the last value is gone.
    """
    return uuid.uuid4().hex


class SessionLeaseService:
    def __init__(self, sessions: SessionStore, leases: SessionLeaseStore) -> None:
        self.sessions = sessions
        self.leases = leases

    async def claim(
        self,
        session: AsyncSession,
        session_id: str,
        agent_id: str,
        request: LeaseRequest,
    ) -> LeaseResponse:
        """Acquire or renew the lease on `session_id` for the calling agent.

        The caller commits. Nothing here writes outside the session and lease
        tables.
        """
        record = await self._require_ownership(session, session_id, agent_id)
        if request.epoch is not None:
            return await self._renew(session, session_id, request)
        return await self._acquire(session, session_id, agent_id, record, request)

    async def _require_ownership(
        self, session: AsyncSession, session_id: str, agent_id: str
    ) -> HostSession | None:
        """The session, if it exists and belongs to this agent.

        A session id is generated by the host and is not a secret, so the
        binding to an agent is the only thing standing between a session and
        whoever guesses its id. `None` means the id is unused and this agent may
        register it.
        """
        record = await self.sessions.get(session, session_id)
        if record is not None and record.agent_id != agent_id:
            raise SessionApiError(
                "NOT_AUTHORIZED",
                f"Session {session_id!r} belongs to another agent.",
                retryable=False,
            )
        return record

    async def _renew(
        self, session: AsyncSession, session_id: str, request: LeaseRequest
    ) -> LeaseResponse:
        """Heartbeat under the epoch the host already holds.

        Renewal never mints a new epoch. A heartbeat that changed the generation
        would invalidate every callback the host is in the middle of, which is
        the opposite of what a heartbeat is for.
        """
        assert request.epoch is not None
        try:
            await self.leases.renew(session, session_id, request.host_id, request.epoch)
        except LookupError as error:
            raise SessionApiError(
                "STALE_EPOCH",
                f"Host {request.host_id!r} does not hold session {session_id!r} "
                f"under epoch {request.epoch!r}. Acquire a lease before emitting.",
                retryable=False,
            ) from error
        return LeaseResponse(
            session_id=session_id, epoch=request.epoch, host_id=request.host_id
        )

    async def _acquire(
        self,
        session: AsyncSession,
        session_id: str,
        agent_id: str,
        record: HostSession | None,
        request: LeaseRequest,
    ) -> LeaseResponse:
        epoch = _mint_epoch()
        if record is None:
            return await self._register(session, session_id, agent_id, epoch, request)

        held = await self.leases.get(session, session_id)
        if held is None:
            return await self._take_free(session, session_id, agent_id, epoch, request)
        return await self._displace(session, session_id, agent_id, epoch, held, request)

    async def _register(
        self,
        session: AsyncSession,
        session_id: str,
        agent_id: str,
        epoch: str,
        request: LeaseRequest,
    ) -> LeaseResponse:
        """First sight of this session: bind it to the agent, then lease it.

        Registration happens here and nowhere else. This is the first moment the
        server has an authenticated agent to bind the id to, and every other
        session route refuses an id nothing has registered.
        """
        try:
            await self.sessions.register(session, session_id, agent_id, request.host_id)
        except SessionAlreadyRegistered as error:
            raise SessionApiError(
                "LEASE_HELD",
                f"Session {session_id!r} was registered by another host while "
                f"this claim was in flight.",
                retryable=True,
            ) from error
        return await self._take_free(session, session_id, agent_id, epoch, request)

    async def _take_free(
        self,
        session: AsyncSession,
        session_id: str,
        agent_id: str,
        epoch: str,
        request: LeaseRequest,
    ) -> LeaseResponse:
        try:
            await self.leases.acquire(
                session, session_id, agent_id, request.host_id, epoch
            )
        except LeaseHeld as error:
            raise SessionApiError(
                "LEASE_HELD",
                f"Session {session_id!r} was leased by another host while this "
                f"claim was in flight.",
                retryable=True,
            ) from error
        await self.sessions.record_host(session, session_id, request.host_id)
        return LeaseResponse(
            session_id=session_id, epoch=epoch, host_id=request.host_id
        )

    async def _displace(
        self,
        session: AsyncSession,
        session_id: str,
        agent_id: str,
        epoch: str,
        held: SessionLease,
        request: LeaseRequest,
    ) -> LeaseResponse:
        """Take a session that already has a holder.

        A holder still heartbeating is refused unless the claimant said it meant
        it. A holder that has stopped is logically free — the same read-time
        staleness `role_leases` uses — so a host that died does not keep its
        session hostage until someone intervenes.

        Either way the incumbent is displaced by the epoch changing under it, not
        by being told. It finds out when its next renew or event is refused,
        which is the only mechanism that also works for a holder that is not
        listening.
        """
        # Read before the swap. `take_over` updates the row this object is
        # mapped to, so afterwards it describes the winner and there is nothing
        # left to name as the loser.
        previous_host = held.host_id
        previous_epoch = held.epoch
        if self.leases.is_live(held) and not request.takeover:
            raise SessionApiError(
                "LEASE_HELD",
                f"Session {session_id!r} is held by host {previous_host!r}, which "
                f"is still alive. Retry with takeover to displace it.",
                retryable=True,
            )
        try:
            await self.leases.take_over(
                session, session_id, previous_epoch, agent_id, request.host_id, epoch
            )
        except LeaseMoved as error:
            raise SessionApiError(
                "LEASE_HELD",
                f"Session {session_id!r} changed hands while this claim was in flight.",
                retryable=True,
            ) from error
        await self.sessions.record_host(session, session_id, request.host_id)
        return LeaseResponse(
            session_id=session_id,
            epoch=epoch,
            host_id=request.host_id,
            displaced=previous_host,
        )
