"""Whether the calling agent may speak for a session at all.

Every session route asks this first and asks it the same way, so it is one
function rather than a copy per service. A session id is generated by the host
and is not a secret: the binding to an agent is the only thing standing between
a session and whoever guesses its id.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from switch_core.bridges.agent.sessions.errors import SessionApiError

if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio import AsyncSession

    from switch_core.db.models import HostSession
    from switch_core.db.stores.session_store import SessionStore


async def owned_session(
    sessions: SessionStore, db: AsyncSession, session_id: str, agent_id: str
) -> HostSession | None:
    """The session, if it exists and belongs to this agent.

    `None` means the id is unused. Only the lease route may act on that — it is
    where registration happens — so every other caller wants
    `require_session` instead.
    """
    record = await sessions.get(db, session_id)
    if record is not None and record.agent_id != agent_id:
        raise SessionApiError(
            "NOT_AUTHORIZED",
            f"Session {session_id!r} belongs to another agent.",
            retryable=False,
        )
    return record


async def require_session(
    sessions: SessionStore, db: AsyncSession, session_id: str, agent_id: str
) -> HostSession:
    """The session, or a refusal.

    An unregistered id is `NOT_FOUND` and a foreign one is `NOT_AUTHORIZED`,
    which does tell a caller holding a valid credential whether an id exists.
    That is the same answer the lease route already gives, and the alternative —
    one code for both — would leave a host unable to tell "I never registered
    this" from "someone else owns it", which are different bugs with different
    fixes.
    """
    record = await owned_session(sessions, db, session_id, agent_id)
    if record is None:
        raise SessionApiError(
            "NOT_FOUND",
            f"No session registered as {session_id!r}. Acquire a lease first.",
            retryable=False,
        )
    return record
