{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "switch.gatewayHost" . }}
  labels:
    {{- include "switch.labels" . | nindent 4 }}
    {{- include "switch.selectorLabels" (dict "Release" .Release "component" "gateway") | nindent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "switch.selectorLabels" (dict "Release" .Release "component" "gateway") | nindent 4 }}
{{- end }}
