apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "switch.fullname" . }}-tuwunel-data
  labels:
    {{- include "switch.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.tuwunel.persistence.size }}
