apiVersion: v1
kind: Service
metadata:
  name: {{ include "switch.tuwunelHost" . }}
  labels:
    {{- include "switch.labels" . | nindent 4 }}
    {{- include "switch.selectorLabels" (dict "Release" .Release "component" "tuwunel") | nindent 4 }}
spec:
  type: {{ .Values.tuwunel.service.type }}
  ports:
    - port: {{ .Values.tuwunel.service.port }}
      targetPort: 8008
      protocol: TCP
      name: http
  selector:
    {{- include "switch.selectorLabels" (dict "Release" .Release "component" "tuwunel") | nindent 4 }}
