import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, parse } from 'node:path';
import type { ServerHost } from './host/types';

/**
 * Dev-only mode: run the managed local stack on the switch-core in the
 * developer's own checkout instead of the released images this build pins.
 *
 * The released path pulls `switch-core:<COMPATIBLE_SWITCH_VERSION>` and friends
 * from GHCR. Here the same compose file is layered with a build override — the
 * same one `just standalone-up` uses — so compose builds `switch`, `gateway`
 * and `setup` from the working tree and tags them under a version of their own.
 *
 * The compose file itself is still the bundled pinned one — only the images
 * change. A checkout whose own `deploy/local/standalone-docker-compose.yml` has
 * moved on (a new service, a new env var) needs the bundled copy re-synced
 * (`pnpm run sync:compose`) before this mode reflects it.
 *
 * It stays a developer tool: {@link findCoreCheckout} only answers when the app
 * is running from a source tree that actually contains the Dockerfiles, and the
 * caller gates it on `import.meta.env.DEV`.
 */

/** Files that identify a Switch checkout root — the compose build context and
 * the Dockerfiles the override names. All must be present, so a half-matching
 * ancestor directory cannot be mistaken for the repo. */
const CHECKOUT_MARKERS = [
  'core/pyproject.toml',
  'deploy/shared_resources/images/Dockerfile.switch',
  'deploy/shared_resources/images/Dockerfile.gateway',
  'deploy/shared_resources/images/Dockerfile.setup',
];

/** Whether `dir` is the root of a Switch checkout the stack can be built from. */
export function isCoreCheckout(dir: string): boolean {
  return CHECKOUT_MARKERS.every((marker) => existsSync(join(dir, marker)));
}

/**
 * The Switch checkout the running app was launched from, or null when it was
 * not launched from one (a packaged install, or a source tree that has been
 * moved away from the repo).
 *
 * Walks up from `startDir` — in `electron-vite dev` the main process runs with
 * the desktop app's directory as its cwd, which is inside the repo.
 */
export function findCoreCheckout(startDir: string = process.cwd()): string | null {
  let dir = startDir;
  const { root } = parse(dir);
  for (;;) {
    if (isCoreCheckout(dir)) return dir;
    if (dir === root) return null;
    dir = dirname(dir);
  }
}

/**
 * The compose override that re-adds the `build:` blocks the published compose
 * file drops, mirroring `deploy/local/standalone-docker-compose.build.yml`.
 *
 * The build context is absolute rather than `.`: compose resolves a relative
 * context against the directory of the file that declares it, and this file is
 * written into the stack's working dir under user-data, not into the checkout.
 */
export function checkoutBuildOverrideYaml(checkoutRoot: string): string {
  const service = (name: string, dockerfile: string) =>
    [
      `  ${name}:`,
      '    build:',
      `      context: ${JSON.stringify(checkoutRoot)}`,
      `      dockerfile: deploy/shared_resources/images/${dockerfile}`,
    ].join('\n');
  return [
    '# Generated by Switch Console — do not edit by hand.',
    '# Dev-only build override: builds the stack images from a local checkout',
    `# (${checkoutRoot}) instead of pulling the pinned released images.`,
    'services:',
    service('switch', 'Dockerfile.switch'),
    service('gateway', 'Dockerfile.gateway'),
    service('setup', 'Dockerfile.setup'),
    '',
  ].join('\n');
}

/** Reading the persisted choice only needs the state directory, not a live
 * host — the same narrowing `ports.ts` makes. */
type HostStateDir = Pick<ServerHost, 'stateDir'>;

function choiceFilePath(host: HostStateDir): string {
  return join(host.stateDir, 'checkout-build.json');
}

/** Whether the developer has turned checkout builds on for this stack. Off
 * unless the file says otherwise, so an unreadable or absent choice can only
 * fall back to the released images. */
export async function isCheckoutBuildEnabled(host: HostStateDir): Promise<boolean> {
  try {
    const parsed: unknown = JSON.parse(await readFile(choiceFilePath(host), 'utf8'));
    return (parsed as { enabled?: unknown } | null)?.enabled === true;
  } catch {
    return false;
  }
}

/** Persist the choice next to the stack's other per-machine metadata. */
export async function setCheckoutBuildEnabled(host: HostStateDir, enabled: boolean): Promise<void> {
  await mkdir(dirname(choiceFilePath(host)), { recursive: true });
  await writeFile(choiceFilePath(host), JSON.stringify({ enabled }, null, 2), 'utf8');
}
