import {
  LOCAL_SERVER_ADMIN_EMAIL,
  LOCAL_SERVER_BIND_ADDR,
  LOCAL_SERVER_MATTERMOST_TEAM,
  LOCAL_SERVER_MATTERMOST_USER,
} from './constants';
import { apiUrlFor, gatewayUrlFor, type LocalServerPorts } from './free-port';
import type { LocalServerSecrets } from './secret-values';

export type LocalServerEnvParams = {
  /** switch-core image tag (COMPATIBLE_SWITCH_VERSION). */
  version: string;
  /** Image registry host (ghcr.io). */
  registry: string;
  /** Image namespace / repo owner. */
  namespace: string;
  /** Free host ports chosen for this machine (published on 127.0.0.1). */
  ports: LocalServerPorts;
  secrets: LocalServerSecrets;
  /**
   * The user's "Share usage data" answer, applied to the server as well as to
   * the app. One consent decision covers both, so this is the toggle's value
   * and nothing else — not a separate server-side preference (CHOO-2890).
   */
  telemetryEnabled: boolean;
};

/** The variable the server reads its telemetry gate from. Named here because
 * reading the choice back off a host has to look for the same key. */
export const TELEMETRY_ENABLED_KEY = 'TELEMETRY_ENABLED';

/**
 * Render the `.env` docker compose interpolates for the local stack. Pure — the
 * host/user values are fixed by the compose contract, ports are chosen per
 * machine, secrets come from the encrypted bundle, and image coordinates are the
 * app's pin. Kept as a pure function so the exact output is unit-testable.
 */
export function buildEnvFile(params: LocalServerEnvParams): string {
  const { version, registry, namespace, ports, secrets, telemetryEnabled } = params;
  return [
    '# Generated by Switch Console local-server mode — do not edit by hand.',
    '# Secrets originate in the app encrypted store; this file is derived.',
    `SWITCH_REGISTRY=${registry}`,
    `SWITCH_IMAGE_NAMESPACE=${namespace}`,
    `SWITCH_VERSION=${version}`,
    `SWITCH_BIND_ADDR=${LOCAL_SERVER_BIND_ADDR}`,
    `GATEWAY_HOST_PORT=${ports.gateway}`,
    `API_HOST_PORT=${ports.api}`,
    `MATTERMOST_HOST_PORT=${ports.mattermost}`,
    `POSTGRES_HOST_PORT=${ports.postgres}`,
    '',
    'DB_HOST=postgres',
    'DB_PORT=5432',
    // The runtime role switch-core actually serves requests as. It owns
    // nothing and is NOBYPASSRLS, so row-level security applies to it — see
    // the `postgres`/`init-db` services in the bundled compose. `postgres`
    // stays the schema owner, bootstrapped as POSTGRES_USER/POSTGRES_PASSWORD
    // below; switch-core migrates and grants as the owner, then serves
    // requests as this role.
    'DB_USER=switch_app',
    `DB_PASSWORD=${secrets.dbRuntimePassword}`,
    'DB_OWNER_USER=postgres',
    `DB_OWNER_PASSWORD=${secrets.dbPassword}`,
    'DB_NAME=switch',
    '',
    'MATRIX_SERVER_NAME=localhost',
    '',
    `AGENT_REGISTRATION_TOKEN=${secrets.agentRegistrationToken}`,
    `JWT_SECRET_KEY=${secrets.jwtSecretKey}`,
    `GATEWAY_ADMIN_EMAIL=${LOCAL_SERVER_ADMIN_EMAIL}`,
    `GATEWAY_ADMIN_PASSWORD=${secrets.gatewayAdminPassword}`,
    `FRONTEND_BASE_URL=${gatewayUrlFor(ports)}`,
    // Turns the "Open in Switch Console" link into an http(s) one. Discord (and any
    // other bridge that only linkifies http) renders a raw `switchdash://`
    // deeplink as dead text, so switch-core rewrites it to point at its own
    // `/deeplink/session`, which 302s back to the deeplink — but only when this
    // is set. It is the API origin, not the operator UI's: the redirect route is
    // served on the agent-bridge app, and this must match the `server` Switch Console
    // reports in the deeplink it is rewriting.
    `GATEWAY_PUBLIC_URL=${apiUrlFor(ports)}`,
    // Written on every start, in both directions. Omitting it when the answer
    // is no would leave a stack that was started under a yes still reporting,
    // because the compose file passes this key through only when the `.env`
    // carries it — so "off" has to be said, not left unsaid.
    `${TELEMETRY_ENABLED_KEY}=${telemetryEnabled ? 'true' : 'false'}`,
    '',
    'MATTERMOST_ADMIN_USER=admin',
    `MATTERMOST_ADMIN_PASSWORD=${secrets.mattermostAdminPassword}`,
    `MATTERMOST_TEAM_NAME=${LOCAL_SERVER_MATTERMOST_TEAM}`,
    `MATTERMOST_USER=${LOCAL_SERVER_MATTERMOST_USER}`,
    `MATTERMOST_USER_PASSWORD=${secrets.mattermostUserPassword}`,
    '',
  ].join('\n');
}

/**
 * One variable's value out of a generated `.env`, unquoted, or null when the
 * file does not carry it (or carries it empty, which compose treats as unset).
 *
 * Lives beside the writer so reading a value back off a host cannot drift from
 * the format that wrote it.
 */
export function readEnvValue(env: string, key: string): string | null {
  const prefix = `${key}=`;
  for (const raw of env.split('\n')) {
    const line = raw.trim();
    if (!line.startsWith(prefix)) continue;
    const value = line
      .slice(prefix.length)
      .trim()
      .replace(/^["']|["']$/g, '');
    if (value.length > 0) return value;
  }
  return null;
}

/**
 * Everything a stack's `.env` pins that another Console needs to run the same
 * stack: the ports it publishes, the credentials its volumes were created with,
 * and the switch-core version it last asked for.
 *
 * `dbRuntimePassword` is null for a `.env` written before switch-core split its
 * database roles (CHOO-2623): that file named the schema owner as `DB_USER`
 * and had no runtime role at all. The caller fills it in rather than refusing —
 * see `withRuntimePassword` in `secret-values.ts` for why that is safe.
 */
export type StackEnv = {
  ports: LocalServerPorts;
  secrets: Omit<LocalServerSecrets, 'dbRuntimePassword'> & { dbRuntimePassword: string | null };
  version: string | null;
};

export type StackEnvReading =
  | { kind: 'complete'; env: StackEnv }
  /** The file is there but does not carry everything a stack needs. Named
   * rather than guessed: minting a replacement for any of these would lock the
   * stack out of a volume the original created, so the caller must refuse or
   * fall back to a copy it trusts — and say which keys were missing. */
  | { kind: 'incomplete'; missing: string[] };

const PORT_KEYS: [keyof LocalServerPorts, string][] = [
  ['gateway', 'GATEWAY_HOST_PORT'],
  ['api', 'API_HOST_PORT'],
  ['mattermost', 'MATTERMOST_HOST_PORT'],
  ['postgres', 'POSTGRES_HOST_PORT'],
];

type PlainSecret =
  | 'agentRegistrationToken'
  | 'jwtSecretKey'
  | 'gatewayAdminPassword'
  | 'mattermostAdminPassword'
  | 'mattermostUserPassword';

const SECRET_KEYS: [PlainSecret, string][] = [
  ['agentRegistrationToken', 'AGENT_REGISTRATION_TOKEN'],
  ['jwtSecretKey', 'JWT_SECRET_KEY'],
  ['gatewayAdminPassword', 'GATEWAY_ADMIN_PASSWORD'],
  ['mattermostAdminPassword', 'MATTERMOST_ADMIN_PASSWORD'],
  ['mattermostUserPassword', 'MATTERMOST_USER_PASSWORD'],
];

function readPort(env: string, key: string): number | null {
  const raw = readEnvValue(env, key);
  if (raw === null || !/^\d{1,5}$/.test(raw)) return null;
  const port = Number.parseInt(raw, 10);
  return port > 0 && port < 65536 ? port : null;
}

/** The two database passwords, from whichever layout wrote the file. */
function readDatabasePasswords(
  env: string,
  missing: string[]
): { dbPassword: string; dbRuntimePassword: string | null } | null {
  const ownerPassword = readEnvValue(env, 'DB_OWNER_PASSWORD');
  if (ownerPassword !== null) {
    const runtimePassword = readEnvValue(env, 'DB_PASSWORD');
    if (runtimePassword === null) {
      missing.push('DB_PASSWORD');
      return null;
    }
    return { dbPassword: ownerPassword, dbRuntimePassword: runtimePassword };
  }
  if (readEnvValue(env, 'DB_USER') === 'postgres') {
    const legacyOwnerPassword = readEnvValue(env, 'DB_PASSWORD');
    if (legacyOwnerPassword === null) {
      missing.push('DB_PASSWORD');
      return null;
    }
    return { dbPassword: legacyOwnerPassword, dbRuntimePassword: null };
  }
  missing.push('DB_OWNER_PASSWORD');
  return null;
}

/**
 * The keys of a stack's `.env` whose values differ from a copy of its settings
 * — empty when the copy agrees with everything the file does carry.
 *
 * For a `.env` that is incomplete: a desktop's copy may fill what the file is
 * missing only when it is demonstrably the same stack's, since a copy from
 * before someone else reset the stack would lock it out of the database the
 * reset created. Only what pins the stack is compared — ports and credentials
 * — not what a start rewrites anyway, such as the version.
 */
export function keysDisagreeing(
  env: string,
  copy: { ports: LocalServerPorts; secrets: LocalServerSecrets }
): string[] {
  const expected = new Map<string, string>();
  for (const [field, key] of PORT_KEYS) expected.set(key, String(copy.ports[field]));
  for (const [field, key] of SECRET_KEYS) expected.set(key, copy.secrets[field]);
  // Which password `DB_PASSWORD` is depends on the layout that wrote the file.
  if (readEnvValue(env, 'DB_OWNER_PASSWORD') !== null) {
    expected.set('DB_OWNER_PASSWORD', copy.secrets.dbPassword);
    expected.set('DB_PASSWORD', copy.secrets.dbRuntimePassword);
  } else if (readEnvValue(env, 'DB_USER') === 'postgres') {
    expected.set('DB_PASSWORD', copy.secrets.dbPassword);
  } else {
    expected.set('DB_PASSWORD', copy.secrets.dbRuntimePassword);
  }
  const disagreeing: string[] = [];
  for (const [key, value] of expected) {
    const found = readEnvValue(env, key);
    if (found !== null && found !== value) disagreeing.push(key);
  }
  return disagreeing;
}

/**
 * Read a stack's generated `.env` back into the values {@link buildEnvFile}
 * wrote it from — the inverse of that function, kept beside it so the two
 * cannot drift.
 *
 * Two layouts are accepted, because a stack keeps whatever file its last start
 * wrote and another Console may be the first to read it after an upgrade:
 *
 * - current: `DB_OWNER_PASSWORD` is the schema owner's (`dbPassword`) and
 *   `DB_PASSWORD` the runtime role's (`dbRuntimePassword`);
 * - before the role split: no `DB_OWNER_PASSWORD`, `DB_USER=postgres`, and
 *   `DB_PASSWORD` the owner's. The runtime password is then null.
 */
export function readStackEnv(env: string): StackEnvReading {
  const missing: string[] = [];

  const ports: Partial<LocalServerPorts> = {};
  for (const [field, key] of PORT_KEYS) {
    const port = readPort(env, key);
    if (port === null) missing.push(key);
    else ports[field] = port;
  }

  const plain: Partial<Record<PlainSecret, string>> = {};
  for (const [field, key] of SECRET_KEYS) {
    const value = readEnvValue(env, key);
    if (value === null) missing.push(key);
    else plain[field] = value;
  }

  const database = readDatabasePasswords(env, missing);

  if (missing.length > 0 || database === null) return { kind: 'incomplete', missing };
  return {
    kind: 'complete',
    env: {
      ports: ports as LocalServerPorts,
      secrets: { ...(plain as Record<PlainSecret, string>), ...database },
      version: readEnvValue(env, 'SWITCH_VERSION'),
    },
  };
}
