import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { LocalServerSecrets } from './secret-values';

export type LocalServerEnvParams = {
  /** switch-core image tag (COMPATIBLE_SWITCH_VERSION). */
  version: string;
  /** Image registry host (ghcr.io). */
  registry: string;
  /** Image namespace / repo owner. */
  namespace: string;
  secrets: LocalServerSecrets;
};

/**
 * Render the `.env` docker compose interpolates for the local stack. Pure — the
 * host/port/user values are fixed by the compose contract, secrets come from the
 * encrypted bundle, and image coordinates are the app's pin. Kept as a pure
 * function so the exact output is unit-testable.
 */
export function buildEnvFile(params: LocalServerEnvParams): string {
  const { version, registry, namespace, secrets } = params;
  return [
    '# Generated by switchdash local-server mode — do not edit by hand.',
    '# Secrets originate in the app encrypted store; this file is derived.',
    `SWITCH_REGISTRY=${registry}`,
    `SWITCH_IMAGE_NAMESPACE=${namespace}`,
    `SWITCH_VERSION=${version}`,
    '',
    'DB_HOST=postgres',
    'DB_PORT=5432',
    'DB_USER=postgres',
    `DB_PASSWORD=${secrets.dbPassword}`,
    'DB_NAME=switch',
    '',
    'MATRIX_SERVER=http://localhost:8008',
    'MATRIX_SERVER_NAME=localhost',
    'MATRIX_ADMIN_USER=admin',
    `MATRIX_ADMIN_PASSWORD=${secrets.matrixAdminPassword}`,
    `MATRIX_REGISTRATION_SHARED_SECRET=${secrets.matrixRegistrationSharedSecret}`,
    '',
    `AGENT_REGISTRATION_TOKEN=${secrets.agentRegistrationToken}`,
    `JWT_SECRET_KEY=${secrets.jwtSecretKey}`,
    'GATEWAY_ADMIN_EMAIL=admin@switch.local',
    `GATEWAY_ADMIN_PASSWORD=${secrets.gatewayAdminPassword}`,
    'FRONTEND_BASE_URL=http://localhost:8000',
    '',
    'MATTERMOST_ADMIN_USER=admin',
    `MATTERMOST_ADMIN_PASSWORD=${secrets.mattermostAdminPassword}`,
    'MATTERMOST_TEAM_NAME=switch',
    'MATTERMOST_USER=user',
    `MATTERMOST_USER_PASSWORD=${secrets.mattermostUserPassword}`,
    '',
  ].join('\n');
}

/** Write the `.env` with owner-only permissions (it holds the stack secrets). */
export async function writeEnvFile(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, { encoding: 'utf8', mode: 0o600 });
  // writeFile only applies `mode` when creating; enforce it on rewrite too.
  await chmod(path, 0o600);
}
