"""Switch's own notices are output, not a request for a reply.

Seen on a Teams 1:1 chat: someone ran `/list-agents`, the bridge answered with
the room roster, and the agent then started a session to respond to that
roster — "Nothing to action there…". It reads as the slash command waking the
agent, and it is not. A direct room addresses its agent with *every* message,
and nothing exempted the admin client's own output.

The second way in is not specific to direct rooms: a notice that lists the
agents present writes each one as `@name`, which tags every one of them.

`ADMIN_MARKER` already means "generated by Switch, do not react to it" — the
admin client honours it. These pin that the agent client does too, while the
message still arrives as ordinary unaddressed context.
"""

from __future__ import annotations

from types import SimpleNamespace

import pytest

from switch_core.clients.admin_messages import ADMIN_MARKER, admin_extra_content
from switch_core.clients.agent_client import AgentClient
from switch_core.clients.room_meta import RoomMeta
from switch_core.delivery.addressing import AddressingResolver
from switch_core.transport import InboundMessage


def _event(body: str, *, admin: bool = False) -> InboundMessage:
    content: dict = {"body": body}
    if admin:
        content.update(admin_extra_content(None))
    return InboundMessage(
        room_id="!room:server",
        event_id="$evt",
        sender="@switch-admin:switch.local",
        timestamp=1,
        content=content,
        body=body,
    )


def _meta(channel_type: str) -> RoomMeta:
    return RoomMeta(room_id="room-1", name="a room", channel_type=channel_type)


def _client(name: str = "flintai-sdk.ts") -> SimpleNamespace:
    """A resolver with the two store-backed checks stubbed out.

    Only the name mention is left live: alias and role routing have their own
    tests, and what these pin is that the marker beats all three.
    """
    resolver = SimpleNamespace(
        agent=SimpleNamespace(name=name),
        matrix_user_id=f"@switch-agent-{name}:switch.local",
    )

    async def _no(*_a: object, **_k: object) -> bool:
        return False

    resolver.mentions_name = lambda **kw: AddressingResolver.mentions_name(
        resolver, **kw
    )
    resolver.addressed_without_lookup = lambda **kw: (
        AddressingResolver.addressed_without_lookup(resolver, **kw)
    )
    resolver.mentions_alias = _no
    resolver.mentions_role = _no
    return resolver


async def _addressed(
    resolver: SimpleNamespace, event: InboundMessage, meta: RoomMeta
) -> bool:
    # `object()` stands in for the session the caller owns: the marker and the
    # name mention are answered before any store is consulted.
    return await AddressingResolver.addresses(
        resolver,
        object(),
        agent=resolver.agent,
        agent_matrix_id=resolver.matrix_user_id,
        room_id=meta.room_id,
        channel_type=meta.channel_type,
        message=AgentClient._as_incoming(event),
    )


@pytest.mark.asyncio
async def test_a_command_result_in_a_direct_room_does_not_address_the_agent() -> None:
    # The reported case: /list-agents in a 1:1 chat, answered by the bridge,
    # and the agent spinning up a session to reply to the answer.
    roster = _event("**Agents in this room:**\n- flintai-sdk.ts", admin=True)

    assert await _addressed(_client(), roster, _meta("direct")) is False


@pytest.mark.asyncio
async def test_a_person_in_a_direct_room_still_addresses_the_agent() -> None:
    # The rule that makes a DM feel like a DM has to survive the fix.
    assert await _addressed(_client(), _event("hello?"), _meta("direct")) is True


@pytest.mark.asyncio
async def test_a_notice_naming_the_agents_present_does_not_tag_them() -> None:
    # In a channel, the self-mention guidance lists "• @name — description" for
    # every agent in the room. Unmarked, that woke all of them.
    notice = _event(
        "👋 You tagged me directly…\n• @flintai-sdk.ts — Claude Code",
        admin=True,
    )

    assert await _addressed(_client(), notice, _meta("channel_public")) is False


@pytest.mark.asyncio
async def test_a_person_tagging_the_agent_in_a_channel_still_addresses_it() -> None:
    tagged = _event("@flintai-sdk.ts can you look at this")

    assert await _addressed(_client(), tagged, _meta("channel_public")) is True


@pytest.mark.asyncio
async def test_the_marker_alone_is_enough_whatever_type_it_carries() -> None:
    # The type is for per-platform rendering; presence is what means "system".
    from switch_core.clients.admin_messages import AdminMessageType

    event = _event("Added flintai-sdk.ts to this room.")
    event.content.update(admin_extra_content(AdminMessageType.COMMAND_RESULT))
    assert ADMIN_MARKER in event.content

    assert await _addressed(_client(), event, _meta("direct")) is False
