"""Switch's own notices are output, not a request for a reply.

Seen on a Teams 1:1 chat: someone ran `/list-agents`, the bridge answered with
the room roster, and the agent then started a session to respond to that
roster — "Nothing to action there…". It reads as the slash command waking the
agent, and it is not. A direct room addresses its agent with *every* message,
and nothing exempted the admin client's own output.

The second way in is not specific to direct rooms: a notice that lists the
agents present writes each one as `@name`, which tags every one of them.

`ADMIN_MARKER` already means "generated by Switch, do not react to it" — the
admin client honours it. These pin that the agent client does too, while the
message still arrives as ordinary unaddressed context.
"""

from __future__ import annotations

from types import SimpleNamespace

import pytest

from switch_core.clients.admin_messages import ADMIN_MARKER, admin_extra_content
from switch_core.clients.agent_client import AgentClient
from switch_core.clients.room_meta import RoomMeta


def _event(body: str, *, admin: bool = False) -> SimpleNamespace:
    content: dict = {"body": body}
    if admin:
        content.update(admin_extra_content(None))
    return SimpleNamespace(
        body=body,
        formatted_body=None,
        sender="@switch-admin:switch.local",
        source={"content": content},
    )


def _meta(channel_type: str) -> RoomMeta:
    return RoomMeta(room_id="room-1", name="a room", channel_type=channel_type)


def _client(name: str = "flintai-sdk.ts") -> SimpleNamespace:
    client = SimpleNamespace(
        agent=SimpleNamespace(name=name),
        matrix_user_id=f"@switch-agent-{name}:switch.local",
    )

    async def _no(*_a: object, **_k: object) -> bool:
        return False

    client._is_mentioned = lambda event: AgentClient._is_mentioned(client, event)
    client._is_mentioned_via_alias = _no
    client._is_mentioned_via_role = _no
    return client


async def _addressed(client: SimpleNamespace, event: object, meta: RoomMeta) -> bool:
    return await AgentClient._compute_addressed(client, event, meta)


@pytest.mark.asyncio
async def test_a_command_result_in_a_direct_room_does_not_address_the_agent() -> None:
    # The reported case: /list-agents in a 1:1 chat, answered by the bridge,
    # and the agent spinning up a session to reply to the answer.
    roster = _event("**Agents in this room:**\n- flintai-sdk.ts", admin=True)

    assert await _addressed(_client(), roster, _meta("direct")) is False


@pytest.mark.asyncio
async def test_a_person_in_a_direct_room_still_addresses_the_agent() -> None:
    # The rule that makes a DM feel like a DM has to survive the fix.
    assert await _addressed(_client(), _event("hello?"), _meta("direct")) is True


@pytest.mark.asyncio
async def test_a_notice_naming_the_agents_present_does_not_tag_them() -> None:
    # In a channel, the self-mention guidance lists "• @name — description" for
    # every agent in the room. Unmarked, that woke all of them.
    notice = _event(
        "👋 You tagged me directly…\n• @flintai-sdk.ts — Claude Code",
        admin=True,
    )

    assert await _addressed(_client(), notice, _meta("channel_public")) is False


@pytest.mark.asyncio
async def test_a_person_tagging_the_agent_in_a_channel_still_addresses_it() -> None:
    tagged = _event("@flintai-sdk.ts can you look at this")

    assert await _addressed(_client(), tagged, _meta("channel_public")) is True


@pytest.mark.asyncio
async def test_the_marker_alone_is_enough_whatever_type_it_carries() -> None:
    # The type is for per-platform rendering; presence is what means "system".
    from switch_core.clients.admin_messages import AdminMessageType

    event = _event("Added flintai-sdk.ts to this room.")
    event.source["content"].update(admin_extra_content(AdminMessageType.COMMAND_RESULT))
    assert ADMIN_MARKER in event.source["content"]

    assert await _addressed(_client(), event, _meta("direct")) is False
