#!/usr/bin/env python3
"""Generate and verify everything declared in artifacts.yaml.

`artifacts.yaml` is the only authored copy of what each Switch artifact is and
what it speaks. Artifacts ship independently and in different languages, so each
needs the registry compiled in — a running artifact cannot ask a file on someone
else's disk what it is.

The alternative is already in the tree and already broken:
COMPATIBLE_SWITCH_VERSION is hand-copied into app-identity.canary.ts, held in
step by a comment reading "keep in sync" and nothing else. uv.lock drifted to a
switch-core version two patches behind pyproject, with nothing to notice.

Two jobs, and the split matters:

* **Generate** the constants nothing else owns. Anything derived from the
  registry is written from it, so it cannot be edited into disagreement.
* **Verify** the ones a packaging ecosystem owns. `importlib.metadata` reads
  pyproject, `npm publish` reads package.json, and both release workflows verify
  the git tag against them. Those files stay authoritative for their tooling —
  generating into them would fight the ecosystem for no gain. The registry is
  checked against them instead, which is enough to stop silent drift.

Usage:
    python scripts/gen_artifacts.py            # write the generated modules
    python scripts/gen_artifacts.py --check    # verify everything, write nothing

`--check` regenerates in memory and compares, so it catches both drift
directions: editing the registry without regenerating, and hand-editing a
generated file. It needs no formatter or toolchain, so CI can run it anywhere.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import tomllib
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "artifacts.yaml"

BANNER_LINES = [
    "Generated from artifacts.yaml by scripts/gen_artifacts.py.",
    "",
    "Do NOT edit this file. Edit artifacts.yaml and run `just artifacts`.",
]

SEMVER = re.compile(r"^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$")


@dataclass(frozen=True)
class Target:
    path: Path
    render: Any


@dataclass(frozen=True)
class Artifact:
    name: str
    description: str
    #: Resolved: an artifact with `version_from` carries its source's version.
    version: str
    #: Where a packaging ecosystem states this version, when one owns it.
    declared_in: str | None
    #: The artifact this one inherits its version from, if it has none of its own.
    version_from: str | None
    #: Where it lands on the registry, for anything we publish.
    published_as: str | None
    pins: dict[str, str]


@dataclass(frozen=True)
class Contract:
    name: str
    description: str
    artifacts: dict[str, tuple[int, int]]


@dataclass(frozen=True)
class Registry:
    artifacts: list[Artifact]
    contracts: list[Contract]


def _squash(text: object) -> str:
    return " ".join(str(text).split())


def load_registry() -> Registry:
    """Parse and validate artifacts.yaml.

    Validation is strict: a malformed registry is a build-time error, never a
    default. Every downstream compatibility answer rests on these numbers.
    """
    raw = yaml.safe_load(SOURCE.read_text())
    if not isinstance(raw, dict):
        raise ValueError(f"{SOURCE} must be a mapping")
    for section in ("artifacts", "contracts"):
        if section not in raw:
            raise ValueError(f"{SOURCE} must have a top-level {section!r} mapping")

    artifacts = [_parse_artifact(name, body) for name, body in raw["artifacts"].items()]
    artifacts = _resolve_inherited_versions(artifacts)
    known = {artifact.name for artifact in artifacts}
    for artifact in artifacts:
        for pinned in artifact.pins:
            if pinned not in known:
                raise ValueError(
                    f"artifact {artifact.name!r} pins {pinned!r}, which is not "
                    "an artifact in this registry"
                )

    contracts = [_parse_contract(name, body) for name, body in raw["contracts"].items()]

    # Every artifact a contract names must exist in the artifacts section.
    # Without this the two halves can disagree about what an artifact even is:
    # `compose` was a peer on stack-compose while the artifacts section had
    # never heard of it, so one name resolved in one half and threw in the
    # other (CHOO-1865).
    for contract in contracts:
        for participant in contract.artifacts:
            if participant not in known:
                raise ValueError(
                    f"contract {contract.name!r} names artifact {participant!r}, "
                    "which is not in the artifacts section — every peer must be "
                    "an artifact this registry knows"
                )

    return Registry(artifacts=artifacts, contracts=contracts)


def _resolve_inherited_versions(artifacts: list[Artifact]) -> list[Artifact]:
    """Give every `version_from` artifact the version it inherits.

    One hop only. A chain would mean an artifact inheriting from something that
    itself has no version of its own, which is a modelling mistake rather than
    a case worth supporting.
    """
    by_name = {artifact.name: artifact for artifact in artifacts}
    resolved: list[Artifact] = []
    for artifact in artifacts:
        if artifact.version_from is None:
            resolved.append(artifact)
            continue
        source = by_name.get(artifact.version_from)
        if source is None:
            raise ValueError(
                f"artifact {artifact.name!r} takes its version from "
                f"{artifact.version_from!r}, which is not an artifact in this registry"
            )
        if source.version_from is not None:
            raise ValueError(
                f"artifact {artifact.name!r} takes its version from "
                f"{artifact.version_from!r}, which has no version of its own"
            )
        resolved.append(replace(artifact, version=source.version))
    return resolved


def _parse_artifact(name: str, body: object) -> Artifact:
    if not isinstance(body, dict):
        raise ValueError(f"artifact {name!r}: expected a mapping")
    description = body.get("description")
    if not description:
        raise ValueError(f"artifact {name!r}: a description is required")

    version = body.get("version")
    version_from = body.get("version_from")
    if (version is None) == (version_from is None):
        raise ValueError(
            f"artifact {name!r}: set exactly one of 'version' (it has its own) "
            "or 'version_from' (it is stamped from another artifact's release)"
        )
    if version_from is not None:
        if not isinstance(version_from, str):
            raise ValueError(f"artifact {name!r}: version_from must be a name")
        if body.get("declared_in") is not None:
            raise ValueError(
                f"artifact {name!r}: declared_in makes no sense with version_from — "
                "nothing declares a version it does not have"
            )
        # Filled in once the source is known.
        version = "0.0.0"
    elif not isinstance(version, str) or not SEMVER.fullmatch(version):
        raise ValueError(
            f"artifact {name!r}: version must be three-part semver, got {version!r}"
        )

    declared_in = body.get("declared_in")
    if declared_in is not None and not isinstance(declared_in, str):
        raise ValueError(f"artifact {name!r}: declared_in must be a path")

    published_as = body.get("published_as")
    if published_as is not None and not isinstance(published_as, str):
        raise ValueError(f"artifact {name!r}: published_as must be a string")

    pins_raw = body.get("pins") or {}
    if not isinstance(pins_raw, dict):
        raise ValueError(f"artifact {name!r}: pins must be a mapping")
    pins: dict[str, str] = {}
    for pinned, pinned_version in pins_raw.items():
        if not isinstance(pinned_version, str) or not SEMVER.fullmatch(pinned_version):
            raise ValueError(
                f"artifact {name!r}: pin of {pinned!r} must be three-part semver, "
                f"got {pinned_version!r}"
            )
        pins[pinned] = pinned_version

    return Artifact(
        name=name,
        description=_squash(description),
        version=version,
        declared_in=declared_in,
        version_from=version_from,
        published_as=published_as,
        pins=pins,
    )


def _parse_contract(name: str, body: object) -> Contract:
    if not isinstance(body, dict):
        raise ValueError(f"contract {name!r}: expected a mapping")
    description = body.get("description")
    if not description:
        raise ValueError(f"contract {name!r}: a description is required")
    artifacts_raw = body.get("artifacts")
    if not artifacts_raw:
        raise ValueError(f"contract {name!r}: at least one artifact is required")

    artifacts: dict[str, tuple[int, int]] = {}
    for artifact, decl in artifacts_raw.items():
        if not isinstance(decl, dict) or set(decl) != {"speaks", "accepts"}:
            raise ValueError(
                f"contract {name!r}, artifact {artifact!r}: "
                "expected exactly 'speaks' and 'accepts'"
            )
        speaks, accepts = decl["speaks"], decl["accepts"]
        for label, value in (("speaks", speaks), ("accepts", accepts)):
            if not isinstance(value, int) or isinstance(value, bool) or value < 1:
                raise ValueError(
                    f"contract {name!r}, artifact {artifact!r}: "
                    f"{label} must be an integer >= 1, got {value!r}"
                )
        if accepts > speaks:
            raise ValueError(
                f"contract {name!r}, artifact {artifact!r}: "
                f"accepts ({accepts}) is above speaks ({speaks}), "
                "which declares an empty range"
            )
        artifacts[artifact] = (speaks, accepts)

    return Contract(name=name, description=_squash(description), artifacts=artifacts)


# ── Reading the versions other ecosystems own ────────────────────────────────


def read_declared_version(relative_path: str) -> str:
    """The version as the owning ecosystem's own file states it."""
    path = REPO_ROOT / relative_path
    if not path.exists():
        raise ValueError(f"declared_in points at {relative_path}, which does not exist")
    if path.suffix == ".toml":
        return str(tomllib.loads(path.read_text())["project"]["version"])
    if path.suffix == ".json":
        return str(json.loads(path.read_text())["version"])
    raise ValueError(f"don't know how to read a version out of {relative_path}")


# Constants that must equal a registry value but cannot be generated, because
# the file holding them is loaded without module resolution — electron-builder
# reads app-identity*.ts under bare Node, where extensionless ESM specifiers do
# not resolve, so those files carry no imports by design. Verified instead,
# which is all that is needed to stop them drifting.
LITERAL_CHECKS: list[tuple[str, str, str]] = [
    (
        "console/apps/switch-console-desktop/src/shared/app-identity.ts",
        "COMPATIBLE_SWITCH_VERSION",
        "switch-console.pins.switch-core",
    ),
    (
        "console/apps/switch-console-desktop/src/shared/app-identity.canary.ts",
        "COMPATIBLE_SWITCH_VERSION",
        "switch-console.pins.switch-core",
    ),
]


def read_ts_literal(relative_path: str, name: str) -> str:
    path = REPO_ROOT / relative_path
    match = re.search(
        rf"export const {re.escape(name)}\s*=\s*['\"]([^'\"]+)['\"]", path.read_text()
    )
    if match is None:
        raise ValueError(f"{relative_path} declares no {name}")
    return match.group(1)


# ── Emitters ─────────────────────────────────────────────────────────────────


def render_python(registry: Registry) -> str:
    lines = ['"""' + BANNER_LINES[0], ""]
    lines.extend(BANNER_LINES[2:])
    lines.append('"""')
    lines.append("")
    lines.append("from typing import Final, NamedTuple")
    lines.append("")
    lines.append("")
    lines.append("class ContractRange(NamedTuple):")
    lines.append('    """The revisions of one contract an artifact implements.')
    lines.append("")
    lines.append("    Two peers are compatible when their ranges overlap; they then")
    lines.append("    operate at the lower of the two `speaks`.")
    lines.append('    """')
    lines.append("")
    lines.append("    speaks: int")
    lines.append("    accepts: int")
    lines.append("")
    lines.append("")
    lines.append("# Where each artifact is. Says nothing about compatibility — that is")
    lines.append("# CONTRACTS below. The two must never be derived from one another.")
    lines.append("ARTIFACT_VERSIONS: Final[dict[str, str]] = {")
    for artifact in registry.artifacts:
        lines.append(f'    "{artifact.name}": "{artifact.version}",')
    lines.append("}")
    lines.append("")
    lines.append("CONTRACTS: Final[dict[str, dict[str, ContractRange]]] = {")
    for contract in registry.contracts:
        lines.append(f"    # {contract.description}")
        lines.append(f'    "{contract.name}": {{')
        for artifact, (speaks, accepts) in contract.artifacts.items():
            lines.append(
                f'        "{artifact}": ContractRange(speaks={speaks}, accepts={accepts}),'
            )
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def contract_range(contract: str, artifact: str) -> ContractRange:")
    lines.append('    """Return an artifact\'s declared range for a contract.')
    lines.append("")
    lines.append("    Raises KeyError for a pair the registry does not know. An")
    lines.append("    unregistered pair is a bug in the caller, never a reason to")
    lines.append("    assume a default — a wrong default reads as compatible.")
    lines.append('    """')
    lines.append("    try:")
    lines.append("        return CONTRACTS[contract][artifact]")
    lines.append("    except KeyError:")
    lines.append("        raise KeyError(")
    lines.append(
        '            f"artifacts.yaml declares no range for artifact {artifact!r} "'
    )
    lines.append('            f"in contract {contract!r}"')
    lines.append("        ) from None")
    lines.append("")
    return "\n".join(lines)


def ts_key(name: str) -> str:
    """Quote an object key only when it is not a bare JS identifier.

    Matches what the repo's formatter would produce, so the generated file is
    a fixed point of `oxfmt` and `--check` needs no formatter to run.
    """
    if name.isidentifier() and name.isascii():
        return name
    return f"'{name}'"


def render_typescript(registry: Registry) -> str:
    lines = ["/**"]
    for banner in BANNER_LINES:
        lines.append(f" * {banner}".rstrip())
    lines.append(" */")
    lines.append("")
    lines.append("/**")
    lines.append(" * The revisions of one contract an artifact implements.")
    lines.append(" *")
    lines.append(" * Two peers are compatible when their ranges overlap; they then")
    lines.append(" * operate at the lower of the two `speaks`.")
    lines.append(" */")
    lines.append("export interface ContractRange {")
    lines.append("  readonly speaks: number;")
    lines.append("  readonly accepts: number;")
    lines.append("}")
    lines.append("")
    lines.append("/**")
    lines.append(
        " * Where each artifact is. Says nothing about compatibility — that is"
    )
    lines.append(
        " * `CONTRACTS` below. The two must never be derived from one another."
    )
    lines.append(" */")
    lines.append("export const ARTIFACT_VERSIONS = {")
    for artifact in registry.artifacts:
        lines.append(f"  {ts_key(artifact.name)}: '{artifact.version}',")
    lines.append("} as const satisfies Record<string, string>;")
    lines.append("")
    lines.append("export type ArtifactName = keyof typeof ARTIFACT_VERSIONS;")
    lines.append("")
    lines.append("/** The release version of an artifact. */")
    lines.append("export function artifactVersion(artifact: ArtifactName): string {")
    lines.append("  return ARTIFACT_VERSIONS[artifact];")
    lines.append("}")
    lines.append("")
    lines.append("export const CONTRACTS = {")
    for contract in registry.contracts:
        lines.append(f"  // {contract.description}")
        lines.append(f"  {ts_key(contract.name)}: {{")
        for artifact, (speaks, accepts) in contract.artifacts.items():
            lines.append(
                f"    {ts_key(artifact)}: {{ speaks: {speaks}, accepts: {accepts} }},"
            )
        lines.append("  },")
    lines.append("} as const satisfies Record<string, Record<string, ContractRange>>;")
    lines.append("")
    lines.append("export type ContractName = keyof typeof CONTRACTS;")
    lines.append("")
    lines.append("/**")
    lines.append(" * Return an artifact's declared range for a contract.")
    lines.append(" *")
    lines.append(
        " * Throws for a pair the registry does not know. An unregistered pair"
    )
    lines.append(
        " * is a bug in the caller, never a reason to assume a default — a wrong"
    )
    lines.append(" * default reads as compatible.")
    lines.append(" */")
    lines.append(
        "export function contractRange(contract: string, artifact: string): ContractRange {"
    )
    lines.append(
        "  const registry = CONTRACTS as Record<string, Record<string, ContractRange>>;"
    )
    lines.append("  const declared = registry[contract]?.[artifact];")
    lines.append("  if (declared === undefined) {")
    lines.append("    throw new Error(")
    lines.append(
        "      `artifacts.yaml declares no range for artifact '${artifact}' in contract '${contract}'`"
    )
    lines.append("    );")
    lines.append("  }")
    lines.append("  return declared;")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


TARGETS = [
    # switch-core: the agent bridge, the gateway API, and the schema check.
    Target(REPO_ROOT / "core" / "switch_core" / "artifacts.py", render_python),
    # Switch Console: the desktop app and the sidecar it bundles and deploys.
    Target(
        REPO_ROOT / "console" / "packages" / "shared" / "src" / "artifacts.ts",
        render_typescript,
    ),
    # agent-runtime: published to a registry, so it cannot depend on the
    # unpublished workspace package above and carries its own copy.
    Target(
        REPO_ROOT
        / "console"
        / "packages"
        / "switch-agent-runtime"
        / "src"
        / "artifacts.ts",
        render_typescript,
    ),
]


def check_declared_versions(registry: Registry) -> list[str]:
    """Compare the registry against the files packaging ecosystems own."""
    problems: list[str] = []
    for artifact in registry.artifacts:
        if artifact.declared_in is None:
            continue
        try:
            actual = read_declared_version(artifact.declared_in)
        except (ValueError, KeyError) as exc:
            problems.append(f"  {artifact.name}: {exc}")
            continue
        if actual != artifact.version:
            problems.append(
                f"  {artifact.name}: artifacts.yaml says {artifact.version}, "
                f"{artifact.declared_in} says {actual}"
            )

    by_name = {artifact.name: artifact for artifact in registry.artifacts}
    for relative_path, constant, source in LITERAL_CHECKS:
        owner, _, pinned = source.partition(".pins.")
        expected = by_name[owner].pins[pinned]
        try:
            actual = read_ts_literal(relative_path, constant)
        except ValueError as exc:
            problems.append(f"  {exc}")
            continue
        if actual != expected:
            problems.append(
                f"  {relative_path}: {constant} is {actual}, but artifacts.yaml "
                f"pins {expected}"
            )
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify everything and write nothing",
    )
    args = parser.parse_args()

    registry = load_registry()
    stale: list[Path] = []

    for target in TARGETS:
        expected = target.render(registry)
        relative = target.path.relative_to(REPO_ROOT)
        if args.check:
            actual = target.path.read_text() if target.path.exists() else None
            if actual != expected:
                stale.append(relative)
            continue
        target.path.parent.mkdir(parents=True, exist_ok=True)
        target.path.write_text(expected)
        print(f"wrote {relative}")

    problems = check_declared_versions(registry)

    if stale:
        print(
            "Generated modules are out of date:\n"
            + "\n".join(f"  {path}" for path in stale)
            + "\n\nEither artifacts.yaml changed without regenerating, or a generated\n"
            "file was hand-edited. Run `just artifacts` and commit the result.",
            file=sys.stderr,
        )
    if problems:
        print(
            "\nartifacts.yaml disagrees with the files it records:\n"
            + "\n".join(problems)
            + "\n\nThese files are owned by their packaging ecosystem, so the registry\n"
            "is checked against them rather than generating into them. Bring the two\n"
            "into agreement — usually by editing artifacts.yaml to match the release.",
            file=sys.stderr,
        )
    if stale or problems:
        return 1

    if args.check:
        print("Registry, generated modules and declared versions all agree.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
