{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "switch.secretName" . }}
  labels:
    {{- include "switch.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "switch.secretData" . | nindent 2 }}
{{- end }}
